Implement pagination for fetch_bans method
hikari-py/hikari pull request #1119
Opened 2022-04-01 01:11 UTC by Jonxslays

### Summary

This pull request implements pagination for `RESTClientImpl.fetch_bans` method.

- It now returns a `LazyIterator[GuildBan]`.
- `GuildBanIterator` added to special_endpoints.

### Checklist

- [x] I have run `nox` and all the pipelines have passed.
- [x] I have made unittests according to the code I have added/modified/deleted.

2022-04-01 03:29 UTC, FasterSpeeding requested changes

2022-04-01 03:29 UTC, FasterSpeeding commented on hikari/impl/special_endpoints.py
> +        first_id: undefined.UndefinedOr[snowflakes.SnowflakeishOr[users.PartialUser]],
can this handle before and after like the message iterator or scheduled event iterator (having a direction and starts_at parameters), its just nicer to not allow passing both at the same time on this level

2022-04-01 03:29 UTC, FasterSpeeding commented on hikari/impl/special_endpoints.py
> +        self._first_id = chunk[-1]["user"]["id"]
> Users will always be returned in ascending order by user_id. 

You need to be calling `chunk.reverse()` before using the chunk when before pagination is used.

2022-04-01 03:29 UTC, FasterSpeeding commented on hikari/api/rest.py
> +        after: undefined.UndefinedOr[snowflakes.SnowflakeishOr[users.PartialUser]] = undefined.UNDEFINED,
This signature would prob be better like fetch_scheduled_event_users where its `newest_first: bool = False, start_at: undefined.UndefinedOr[snowflakes.SnowflakeishOr[users.PartialUser]]` which would make the note about before vs after unnecessary

2022-04-08 12:12 UTC, FasterSpeeding commented on changes/1119.feature.md
> +Add `GuildBanIterator` to `special_endpoints`.
This addition doesn't need to be added to the changelog

2022-04-09 06:16 UTC, FasterSpeeding approved these changes

2022-04-09 06:56 UTC, davfsa reviewed
Just 2 small things, everything else LGMT!

2022-04-09 06:56 UTC, davfsa commented on changes/1119.breaking.md
> +Return `LazyIterator[GuildBan]` from `RESTClientImpl.fetch_bans` instead of `Sequence[GuildBan]`.
This really doesnt give any information to unexperienced users.

Something along these lines instead?
```suggestion
`RESTClientImpl.fetch_bans` now return a `LazyIterator` to allow pagination of values.
```

Also, this isnt really breaking as awaiting the iterator will just cause the same functionality as before. I would probably label this as a bugfix.

2022-04-09 06:56 UTC, davfsa commented on hikari/api/rest.py
> +            See `hikari.iterators` for the full API for this iterator type.
Just to make my life easier, mind moving this on top of all the other sections? Part of docs v2 pr :)

2022-04-09 15:18 UTC, davfsa approved these changes

2022-04-09 22:10 UTC, FasterSpeeding approved these changes

2022-04-09 22:10 UTC, merged