add retry on timeout
hikari-py/hikari pull request #1132
Opened 2022-04-12 20:12 UTC by Le0Developer

### Summary

Retry on `asyncio.TimeoutError` that aiohttp raises when a request times out.

Currently testing this in production, hence draft, no changelog fragment and a lack of formatting/tests.

### Checklist

- [ ] I have run `nox` and all the pipelines have passed.
- [ ] I have made unittests according to the code I have added/modified/deleted.

2022-04-14 14:33 UTC, Le0Developer commented
No idea what to do about the flake8 max complexity error 🤷

2022-04-14 18:26 UTC, davfsa commented
I am a bit torn on this. It is similar to a similar PR I did some time ago to attempt a restart on timeout errors.

Now that I think about it, it might be better to just recommend people to edit their HTTPSettings to their liking if they see this error too often.

cc @FasterSpeeding Opinions?

2022-05-05 13:24 UTC, Le0Developer commented
Added aiohttp.ClientOSError to retry too.

2022-07-14 16:47 UTC, davfsa commented
> Tbh not exactly sure what you're getting at there, wdym by restart?

Currently, if any error is thrown while doing the initial request to fetch the sharding information when the bot is being started, it just exits with an error.

I had the idea of at least retrying that request but eventually scrapped it and just decided on just recommending people to edit their HTTPSettings to have no timeout or a higher one on unstable connections

2022-07-14 16:50 UTC, FasterSpeeding commented
> I had the idea of at least retrying that request but eventually scrapped it and just decided on just recommending people to edit their HTTPSettings to have no timeout or a higher one on unstable connections

Is this related to that though? Doesn't `asyncio.TImeoutError` and `aiohttp.ClientOSError` being raised effect all requests, not just startup and since they're not being caught currently unless i'm missing something changing HTTPSettings wouldn't help with that?

2022-07-14 16:52 UTC, davfsa commented
> Is this related to that though? Doesn't `asyncio.TImeoutError` and `aiohttp.ClientOSError` being raised effect all requests, not just startup and since they're not being caught currently unless i'm missing something changing HTTPSettings wouldn't help with that?

Initially this pr was for `asyncio.TimeoutError` only, it later got extended to include `aiohttp.ClientOSError`, which I wasn't talking about in that comment.

And yes, when the timeout is exceeded, aiohttp raises a timeout error.

The comment I made before is about a change I worked on but never made (which only thought about timeout errors), since I abandoned it.

2023-01-01 20:34 UTC, FasterSpeeding approved these changes

2023-01-01 20:37 UTC, davfsa commented
Personally dont like the current state of the PR, will comment on it later :)

2023-01-01 20:38 UTC, FasterSpeeding commented
It needs rebasing now anyways lol

2023-01-02 08:56 UTC, davfsa requested changes
@Le0Developer would you mind showing me some context on this PR? Mostly these issues:
- Under what situations are you seeing the `asyncio.TimeoutError`? And wouldnt it be nicer to just tweak your `hikari.impl.HTTPSetting.timeouts` and tweak the values there (potentially only `total`)
  - This already defaults to 30 seconds, so the fact that you are seeing so many of them is a bit worrying. Might want to double check the network to the raspberry pi is stable (try using an ethernet cable directly to the router, if not done already)
- `aiohttp.ClientOSError` is a really weird case and not something i have seen in a while, specially on linux. Mind trying to upgrade hikari + aiohttp to their respective latest versions and give it another shot?

*Sorry that this took so long, I kinda forgot about this pr 😅*

2023-01-02 08:56 UTC, davfsa commented on hikari/impl/rest.py
> +    async def _request(  # noqa: C901 CFQ001
```suggestion
    async def _request(  # noqa: C901 CFQ001
```
If these are ignored, they should also be documented above

2023-01-02 08:56 UTC, davfsa commented on hikari/impl/rest.py
> +                    try:
The try except should be taken out of here and put before the `with` (in the base of this PR, a try already exists there, but it is not there in the current state of master, so a rebase will first be necessary)

2023-01-02 08:56 UTC, davfsa commented on hikari/impl/rest.py
> +                            "Timed out on request, backing off for %.2fs and retrying. Retries remaining: %s",
Since we catch `aiohttp.ClientOSError` too, this is no longer true

2023-01-03 15:58 UTC, Le0Developer commented
> Might want to double check the network to the raspberry pi is stable (try using an ethernet cable directly to the router, if not done already)

My raspberry pi is directly plugged into my router, it just happens *sometimes* (possibly happens when internet connection is shortly cutoff?).

> `aiohttp.ClientOSError` is a really weird case and not something i have seen in a while, specially on linux.

I only have the discord notification of sentry, since sentry deletes them after 90d:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/40232557/210393692-be403e95-038d-4364-8fdc-e2dde17d625a.png">

2023-01-03 22:24 UTC, davfsa commented
> My raspberry pi is directly plugged into my router, it just happens sometimes (possibly happens when internet connection is shortly cutoff?).

After a 30s timeout, i think the issue might be bigger than just a simple timeout, but regardless, maybe this is worth implementing for the few it would affect

> I only have the discord notification of sentry, since sentry deletes them after 90d

Hmmm. Under normal functions you should be receiving this, but i guess we could handle it for the odd case

2023-06-25 20:21 UTC, davfsa commented
Closing in favor of https://github.com/hikari-py/hikari/pull/1648

2023-06-25 20:21 UTC, closed without merging