Added missing documenation.
hikari-py/hikari pull request #1958
Opened 2024-07-07 05:07 UTC by mplatypus

### Summary
Added documentation to `ShardCloseCode` and `AuditLogEventType`

### Checklist
- [x] I have run `nox` and all the pipelines have passed.
- [x] I have made unittests according to the code I have added/modified/deleted.

### Related issues
Nothing related.

2024-07-07 17:54 UTC, davfsa requested changes
Thanks for the pull request!

Couple of notes:
- Docstrings should begin and end with `"""`, not `"`
- I am not too sure about adding documentation to the shard close codes, but I wouldn't mind it. It seems a bit arbitrary

2024-07-07 17:54 UTC, davfsa commented on hikari/audit_logs.py
> +    "App was updated (as an example, its scopes were updated)."
```suggestion
     INTEGRATION_UPDATE = 81
    """An integration was updated.

    For example, its scopes were updated.
    """
```

2024-07-07 17:56 UTC, davfsa commented
Also, changelog fragment is missing :)

2024-07-09 10:00 UTC, mplatypus commented
@davfsa
> * I am not too sure about adding documentation to the shard close codes, but I wouldn't mind it. It seems a bit arbitrary

What about the 4000-4999? as found here [mdn](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent/code) it does state that those close codes are private, and therefore unique. I was thinking adding it to all of them just looked nicer imo.

2024-07-09 10:03 UTC, davfsa commented
Yeah, that's part of the spec, 4xxx range is for individual use after agreement. It's fine leaving them documented ig.

Would you mind fixing the docstring issue (wrapping with triple quotes instead of single) and I think this is good to merge

2024-07-09 10:06 UTC, mplatypus commented
was literally just doing that right now haha.

2024-08-10 14:40 UTC, closed without merging