Add endpoints and objects for handling templates.
hikari-py/hikari pull request #392
Opened 2020-12-15 02:20 UTC by FasterSpeeding

### Summary
Add endpoints and objects for handling templates.

### Checklist

- [x] I have run `nox` and all the pipelines have passed.
- [x] I have made unittests according to the code I have added/modified/deleted.

### Related issues

2020-12-15 02:46 UTC, FasterSpeeding commented on hikari/api/rest.py
> +    async def create_guild_from_template(
Missed this doc: TODO

2020-12-15 02:56 UTC, FasterSpeeding commented on hikari/guilds.py
> +@attr_extensions.with_copy
This is unnecessary, should be inherited

2020-12-16 07:34 UTC, davfsa requested changes
For the rest, LGTM

2020-12-16 07:34 UTC, davfsa commented on hikari/api/rest.py
> +
`@abc.abstractmethod` are missing from all of these

2020-12-16 09:17 UTC, davfsa approved these changes

2020-12-16 10:23 UTC, davfsa approved these changes

2020-12-16 11:41 UTC, merged