On our way to 100% coverage
hikari-py/hikari pull request #562
Opened 2021-04-25 11:25 UTC by davfsa

### Checklist

- [x] I have run `nox` and all the pipelines have passed.
- [x] I have made unittests according to the code I have added/modified/deleted.

2021-04-28 23:00 UTC, FasterSpeeding requested changes

2021-04-29 06:19 UTC, davfsa commented on hikari/embeds.py
> +        self._color = colors.Color.of(color) if color else None
That should be `colour is not None`, will fix

2021-04-29 06:20 UTC, davfsa commented on tests/hikari/internal/test_enums.py
> +        assert TestFlag.FOO.__index__() == 0x312
The function we were using for this before is `operations.index(obj)` which, for some reason doesn't make it count towards coverage

2021-04-29 06:30 UTC, FasterSpeeding commented on tests/hikari/internal/test_enums.py
> +        assert TestFlag.FOO.__index__() == 0x312
That doesn't change the fact that this change allows for erroneous behaviour down the line

2021-05-01 14:41 UTC, FasterSpeeding approved these changes

2021-05-01 15:08 UTC, merged