Implement Stage instances
hikari-py/hikari pull request #695
Opened 2021-07-09 16:23 UTC by ashwinvin

### Summary
Implements Stage Instances

### Checklist
- [x ] I have run `nox` and all the pipelines have passed.
- [ ] I have made unittests according to the code I have added/modified/deleted.

### Related issues
Closes #602

2021-09-01 17:21 UTC, FasterSpeeding requested changes

2021-09-01 17:21 UTC, FasterSpeeding commented on hikari/api/event_factory.py
> +        """Parse a raw payload from Discord into a Stage instance create event object.
Don't think Stage needs to be capitalised in these descriptions

2021-09-01 17:21 UTC, FasterSpeeding commented on hikari/api/rest.py
> +            If the interaction or response is not found.
stage instance not interaction

2021-09-01 17:21 UTC, FasterSpeeding commented on hikari/api/rest.py
> +            `builtins.None` if no Stage instance exists in the stage channel.
This doesn't match the type hint

2021-09-01 17:21 UTC, FasterSpeeding commented on hikari/api/rest.py
> +
This space between the parameters is unnecessary

2021-09-01 17:21 UTC, FasterSpeeding commented on hikari/api/rest.py
> +            If you are unauthorized to make the request (invalid/missing token).
The permissions behaviour should be mentioned here

2021-09-01 17:21 UTC, FasterSpeeding commented on hikari/api/rest.py
> +            If the interaction or response is not found.
All these NotFoundError raise reasons need to be updated

2021-09-01 17:21 UTC, FasterSpeeding commented on hikari/events/stage_events.py
> +        """Stage Instance that this event relates to.
the app property should be implemented on StageInstanceEvent

2021-09-01 17:21 UTC, FasterSpeeding commented on hikari/events/stage_events.py
> +    def stage_instance_id(self) -> snowflakes.Snowflake:
instance_id can be implemented here also i think "instance_id" would be a cleaner name

2021-09-01 17:21 UTC, FasterSpeeding commented on hikari/stage_instances.py
> +    discoverable_disabled: bool = attr.field(eq=False, hash=False, repr=False)
I assume this field is a moderation thing on discord's end but whatever it is should be clarified in the field's docstring. Also the name of this field should probably be changed to indicate that it's a bool field

2021-09-01 17:21 UTC, FasterSpeeding commented on hikari/stage_instances.py
> +        This will be empty if the channels are missing from the cache.
it won't be "empty", it'll return None

2021-09-01 17:21 UTC, FasterSpeeding commented on hikari/stage_instances.py
> +            The guild stage channel where this stage instance was created.
This doesn't match up with the type hint

2021-09-01 17:21 UTC, FasterSpeeding commented on hikari/stage_instances.py
> +            If any invalid snowflake IDs are passed; a snowflake may be invalid
They aren't passing IDs here

2021-09-01 17:21 UTC, FasterSpeeding commented on hikari/stage_instances.py
> +        If not known, this will return `builtins.None` instead.
better to say "not cache" than "not known"

2021-09-01 17:21 UTC, FasterSpeeding commented on hikari/stage_instances.py
> +            If the guild is not found.
GET guilds/{guild.id} never returns NotFoundError

2021-09-08 12:04 UTC, davfsa commented
Please check comments FasterSpeeding made as well as rebase to master to fix merge conflicts. 

Please also have a look at https://github.com/hikari-py/hikari/blob/master/CONTRIBUTING.md#towncrier on how to use towncrier to document the changes you made

2021-09-25 15:33 UTC, FasterSpeeding commented
I'ma take over/finish these PRs next week (I've already talked about this with Ashu)

2023-09-28 15:13 UTC, davfsa commented
Closing in favor of #1725

2023-09-28 15:13 UTC, closed without merging