Add display_avatar_url property for Member & User
hikari-py/hikari pull request #975
Opened 2022-01-22 02:56 UTC by HyperGH

### Summary
It is somewhat tedious to get an `avatar_url` that is guaranteed to always exist, this property aims to rectify this issue, and simplify getting avatars somewhat.

### Checklist
- [x] I have run `nox` and all the pipelines have passed.
- [ ] I have made unittests according to the code I have added/modified/deleted.

2022-01-22 08:18 UTC, davfsa requested changes
Thank you for the PR. Could you please add tests and the change log fragment file for this change?

Additionally, could you also add a `display_name` attribute? Should be similar to this one in both `User` and `Member`

If you have any questions on how to do that, please check CONTRIBUTING.md or ask us :)

2022-01-22 08:19 UTC, FasterSpeeding requested changes

2022-01-22 08:19 UTC, FasterSpeeding commented on hikari/guilds.py
> +        return self.guild_avatar_url or self.avatar_url or self.default_avatar_url
```suggestion
        return self.guild_avatar_url or super().display_avatar_url
```

Would help avoid duplication here

2022-01-22 08:19 UTC, FasterSpeeding commented on hikari/users.py
> +        return self.avatar_url or self.display_avatar_url
```suggestion
        return self.avatar_url or self.default_avatar_url
```

Is probably what you actually wanted here

2022-01-23 15:42 UTC, HyperGH commented
> Thank you for the PR. Could you please add tests and the change log fragment file for this change?
> 
> If you have any questions on how to do that, please check CONTRIBUTING.md or ask us :)

Done!

2022-01-23 22:58 UTC, davfsa submitted a review, later dismissed

2022-01-23 23:10 UTC, FasterSpeeding commented on hikari/users.py
> +        return self.avatar_url or self.default_avatar_url
Missing test coverage

2022-01-25 10:04 UTC, davfsa commented on hikari/users.py
> +        return self.avatar_url or self.default_avatar_url
Deleted the wrong comment while doing my review by mistake (*Original comment by snab*):

"Missing test coverage"

2022-01-25 10:05 UTC, davfsa commented on hikari/users.py
> +        return self.avatar_url or self.default_avatar_url
Would it be worth avoiding a call less here and just doing

```suggestion
        return self.make_avatar_url() or self.default_avatar_url
```

2022-01-28 14:27 UTC, FasterSpeeding approved these changes

2022-01-28 14:42 UTC, merged